### ISSUE TITLE
Put oversize warning in default game running page

### ISSUE THREAD

**Issue by tjpalmer** [aduros/wasm4#223]
For the default game running page (such as in `w4 watch`), there should be a clear warning off the side of the game when the file is over 64k, so people are aware of that.

**Comment by aduros** [comment]
In `w4 run/watch` (devkit mode), oversize games should print a warning the console if too large but continue to load. This is important so that games built with debug symbols still work during development.

For `w4 bundle` outputs and games hosted on wasm4.org, we should refuse to load oversize games and crash with an error.
