### ISSUE TITLE
Racer on wasm4 site blue-screens on 'R'

### ISSUE THREAD

**Issue by sporksmith** [aduros/wasm4#273]
https://wasm4.org/play/racer/

With the game running, hitting 'r' gives a wasm4 bluescreen for me on Firefox. It doesn't happen in other games on the site.

**Comment by DenialAdams** [comment]
I wonder if this is because the reset happens asynchronously with the game update, i.e.:

1) R is pressed, onkeypress fires, memory is reset, wasm begins to instantiate and await causes javascript to resume executing (https://github.com/aduros/wasm4/blob/main/runtimes/web/src/index.js#L102)
2) Request animation frame triggers, update is called while wasm is still being instantiated so old wasm module is still called

Though I'm not very familiar with the JavaScript async execution model so maybe that can't happen. I'll test this theory out

(pasted from discord.)

---

Currently struggling to get a local wasm4 web runtime building, but hopefully I can test this out soon

**Comment by DenialAdams** [comment]
> It doesn't happen in other games on the site.

You can actually see this problem in games other than Racer too, even if they don't crash. If I reset my game "endless runner" many times, I occasionally see some weird graphics for ~1 frame. After #283 (looking at the netlify preview), I can't cause that to occur
