### ISSUE TITLE
Can't build wasm web runtime

### ISSUE THREAD

**Issue by DenialAdams** [aduros/wasm4#281]
`npm install` in the web runtime is failing for me:

```
root@me ~/wasm4/runtimes/web (git)-[main] # npm install
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! code 2
npm ERR! path /root/wasm4/devtools/web
npm ERR! command failed
npm ERR! command sh -c npm run clean && npm run build
npm ERR! > @wasm4/web-devtools@1.0.0 clean
npm ERR! > rimraf dist types
npm ERR!
npm ERR!
npm ERR! > @wasm4/web-devtools@1.0.0 build
npm ERR! > tsc && vite build
npm ERR!
npm ERR! src/components/controls-view/controls-view.ts(1,34): error TS2307: Cannot find module 'lit' or its corresponding type declarations.
npm ERR! src/components/controls-view/controls-view.ts(2,41): error TS2307: Cannot find module 'lit/decorators.js' or its corresponding type declarations.
npm ERR! src/components/devtools/devtools.ts(1,34): error TS2307: Cannot find module 'lit' or its corresponding type declarations.
```

There are many more errors after that, but I truncated the list. I also had to install tsc and rimraf, which is fine.

**Comment by FaberVitale** [comment]
You need to download the devtools dependencies on your machine:

```bash
npm --prefix devtools/web/ i
```

Other things to remember:

- use npm 7 or higher: it seems that @aduros uses that npm version and prefers lockfile version 2.
  If you have [nvm](https://github.com/nvm-sh/nvm) run `nvm use 16`(run `nvm install if necessary`) to use npm 7.

---

### Context

We've talked about switching to a monorepo setup in order to simplify the development but it is on the todo list.

**Comment by aduros** [comment]
@FaberVitale Can you please update the web runtime README with the devtools building step?

I wonder if we can make building the devtools optional somehow? Although it's just one extra step.

**Comment by FaberVitale** [comment]
> @FaberVitale Can you please update the web runtime README with the devtools building step?

It actually gets build automatically when you do npm install inside `runtime/web` but the builds fails because `devtools/web/` doesn't have its dependencies installed.

I can add a readme but this whole thing should be resolved with:

1. add monorepo setup, preferably yarn. A simple `npm i` or `yarn` would install all dependecies and symlink the dependencies.

2. A `developing.md` page that explains how to setup work with the project especially for people that aren't familiar with node.js. 

> I wonder if we can make building the devtools optional somehow? Although it's just one extra step.

Not the way it is currently setup it would fail during compilation.
