### ISSUE TITLE
native runtime: MiniFB runs slow

### ISSUE THREAD

**Issue by JerwuQu** [aduros/wasm4#326]
I noticed that when playing music on the native runtime on Windows, it was much slower than on web or on my linux laptop. Did a quick BPM tap and saw that it was almost 20% slower.

I added basic FPS calculation to the MiniFB update loop and it's hovering in the range of 51-53 fps (on my computer), despite the FPS target being set to 60. Raising the MiniFB target FPS (via `mfb_set_target_fps`) to 62 gets it to land at around 60, so it's definitely not a performance issue.

I'd assume a contributing factor is my monitor refresh-rate is 144hz (which is indivisible by 60), but I haven't looked into details yet.

**Comment by JerwuQu** [comment]
Investigated and opened a PR upstream https://github.com/emoon/minifb/pull/81

**Comment by Darky-Lucera** [comment]
I have to change a little bit the PR because it has a typo (0.003d) and you don't send the changes in CMakeLists.txt (link against winmm.lib) and WindowData_Win.h (to be able to use timer services WIN32_LEAN_AND_MEAN cannot be defined, almost under MinGW).

In any case, the PR is accepted and changes are already committed. Thanks a lot!

Note: If you want to render text in MiniFB, or any other frame buffer, you can use this lib: https://github.com/Darky-Lucera/FontRenderer that I'm working on. For now only C++ but I'm planning to add a C interface soon.

**Comment by JerwuQu** [comment]
Merged upstream so just bump the submodule whenever :)

**Comment by aduros** [comment]
Minifb updated!
