### ISSUE TITLE
ADSR specification 

### ISSUE THREAD

**Issue by micaevski** [aduros/wasm4#331]
Hey there!
I just started playing with WASM-4 yesterday and I'm really enjoying it! Thank you all who are involved. 

I am building a step sequencer and I realised that the ADSR parameters of the tone function are not what you would call "Standard". 

Maybe it's some vintage specification, I don't know but usually you would have a them specified as 
Attack - time to reach the set volume level
Decay -  time to reach the sustain volume level
Sustain -  a secondary volume level that is sustained through the duration of the note. 
Release - time after the release of the note until the volume has reached 0.
This of course relies on the note having a duration. 

The current specification leads to all sorts of weird states like having volume when the volume is all the way down or really big jumps in volume just because you introduced some attack.
Also there is no way to add attack and decay but still be able to mix your tone at a lower level than maximum.

It would be really great if the `tone` function had a duration parameter so the specification could change. 

something like
`tone(freq1, envelope, duration | (volume << 16), flags)`

or even better 

`tone(freq, ampAttack | (ampDecay << 16), ampSustain | (ampRelease << 16), freqAttack | (freqDecay << 16), freqSustain | (freqRelease << 16), duration | (volume << 16), flags)` 

The envelope parameters are split so the sustain part of the frequency envelope will now have 16bits, enough to describe the sustained frequency. 
The amp sustain could be a full independent volume level or something relative to the volume parameter.

I think this allows more musical variety and is much more resembling of how synthesisers work. 

Thanks again.

**Comment by JerwuQu** [comment]
I noticed this too. As far as I understood from my testing, how it works right now is that `volume` parameter is what would be Sustain in ADSR, and that a tone amplitude parameter doesn't exist, it's instead locked to 100%, making it impossible to set amplitude if you also want to use ADSR.

It would be a breaking change, but I definitely think it's worth considering making it more in line with the norm, since right now it's a bit weird.

I don't think we need 16 bits of precision for ADSR like in your examples though, and mixing duration and volume into the same bitfield might be a bit strange (since they're not related).
I personally like `tone(freq, duration, volume, adsr, flags)` better since it's easier to use for people that don't need the advanced features.
It would be used as `tone(freq1 | (freq2<< 16), duration, volume, (a << 24) | (d << 16) | (s << 8) | r), flags)`.
If following ADSR, only the `r` length would actually get added onto the total duration. Right now all of them are added together.

I don't think @aduros is interested in a change that would break pretty much all games using audio, but if other breaking changes are planned, I think this one should be high on the list.

**Comment by marler8997** [comment]
One idea that comes to my mind is that there's all kinds of envelopes that one may want.  If we're going to break the current one, could we support a mechanism that would any any sort of envelope?

What if we had the ability to "change" a note without retriggering it, and add a "transition duration" value between the old note value and the new note value.  Such a mechanism could even remote the need for having 2 frequencies, since this could be implemented by calling "tone" 2 times with different frequencies and specifying a transition time.  We could do the same thing to change the volume which would allow people to craft any sort of envelope they need.

**Comment by micaevski** [comment]
I admit, I was just cramming parameters together, I'm new to this "gotta save 16 bits" mode of programming. 
My main issues are:
1. Not being able to set the max volume (to volume reached by the attack phase) - this also makes hard to have an overall volume control.
2. Sustain being a time parameter and not a secondary volume.

It's like @JerwuQu described,  you are always stuck with 100% than the sustain is the time spent at the set volume level.
I don't mind not having a dedicated pitch envelope using the current simple setup. 

I just joined the discord so I can get involved.

**Comment by rohlem** [comment]
Note you can already create any envelope shape you want by chaining calls to `tone`.
Note a single `update` can submit multiple `tone` requests for the same channel. When playing on a currently-active channel, the phase and current volume level are retained and the ADSR is started in-place (since #229):
  - If you want to increase the volume, you can use the attack-phase of a new `tone`, which will start from current volume and slowly rise to 100%. (Adjust the attack length and cut it off with a new `tone` before reaching 100% if you only want a partial increase.)
  - If you want to decrease the volume, you can use the "decay" (or technically also the "release") phase of `tone` in the same way.
  - For immediate volume jumps, you can interject with a sustain-only `tone` command of the desired volume. 

I'm not saying that the current interface couldn't be made more ergonomic, just pointing out what is already possible. IMO the current granularity, which is below 1% change per frame, is already pretty accurate.

**Comment by JerwuQu** [comment]
This is great information, though it feels like a workaround. Looks like it wouldn't work in the sample based playback used on native (and currently being ported to web dded713115e72ac8f5d72f866fce84e9d7ddf4db)...?

**Comment by micaevski** [comment]
I will play around with it and see how expressive it feels for music applications. 
Still, I'm convinced that any developer with background in music production or synthesis will consider the current ADSR a bug, since it does not work as expected.

**Comment by aduros** [comment]
Hi all, thank you for the well-written feedback!

Currently the attack peak amplitude is hardcoded to 100% volume. How about using the high 16 bits of `tone`'s volume parameter to set the peak volume? A change like this could be simple and backwards compatible.

Also a bit of background about the design of `tone`. The idea was to have a single function for sound that works for both simple and advanced uses. The bit shifting stuff isn't so much to save 16 bits, but to have a simple and approachable API by default while also enabling (slightly hidden) advanced features like ADSR and frequency slides. I feel like this is better for learnability than having several versions of `tone` to choose from (eg: `toneSimple`, `toneADSR`, `toneSlide`).

**Comment by joshgoebel** [comment]
Did we consider memory mapped sounds vs a single API that is forced to "do it all"?

**Comment by JerwuQu** [comment]
> How about using the high 16 bits of `tone`'s volume parameter to set the peak volume? A change like this could be simple and backwards compatible.

I think this is the most elegant solution to fix this without breaking the API! Shifting 8 bits would be enough (since max is 100) if we want to leave room for other shenanigans (e.g. maybe some day tremolo or vibrato becomes interesting).

**Comment by micaevski** [comment]
>Currently the attack peak amplitude is hardcoded to 100% volume. How about using the high 16 bits of tone's volume parameter to set the peak volume? A change like this could be simple and backwards compatible.

That would be much more usable. 

>EDIT: Some rephrasing in the documentation might be good afterwards though. What is currently volume should be sustain, the new shifted bits would be amplitude/volume, and what is currently named sustain should be sustain duration. Just rephrasing what is currently used so it makes more sense to music people, not changing how it behaves.

Agreed.  It's not standard specification but it would make much more sense than the current state.
