### ISSUE TITLE
When saving is not supported, save data is not retained across frames

### ISSUE THREAD

**Issue by pfgithub** [aduros/wasm4#351]
Sample cartridge: https://pfg.itch.io/plctfarmer

The web build doesn't work if localstorage is blocked in the browser

Discord link: https://discord.com/channels/918503626333356072/928662139844059166/934274631597166592

https://user-images.githubusercontent.com/6010774/150621996-3b76c977-b051-4a72-bb5d-54da3b6757d3.mp4

**Comment by JerwuQu** [comment]
I thought about this a bit, and maybe it should be up to the developer to handle this instead?
`diskw` returns the amount of bytes written, so if this returns 0 you can assume that the save failed (and that the console can't save). Maybe it doesn't return 0 in this condition today though. It kinda makes more sense, since it would be strange for `diskr` to return data if it hasn't actually been saved.

**Comment by aduros** [comment]
Does anyone have any thoughts about what we should do here, if anything?

We could add an in-memory storage to fix cases like this, but then games won't know if saved data is actually being persisted. The native runtime currently works this way.

**Comment by joshgoebel** [comment]
I do like the idea of returning 0 (or an error code) when a save "fails"... OR you say that save never fails and the only thing that fails is persistence - IE, in memory storage... but if we did that I'd think you'd want some UI in the web player that told you that localstorage was disabled and saves wouldn't be persisted?

**Comment by JerwuQu** [comment]
I feel like this is only a problem for games that read the disk several times during playthrough (rather than just in `start()`) and overwrite their current state even when `diskr` returns 0.
I think it's better to indicate to the player that saves/disks aren't working than to mock an ephemeral disk.

**Comment by christopher-kleine** [comment]
I agree. I think it's better to return the amount of written bytes. And if it's 0, the game has to handle it. In the days of PS1/PS2 it was not much different.
True, the game was able to detect if a memory card was available ... and prepare for this. But the same can be true here. If `diskr` returns 0, you know that you can neither read nor write.

**Comment by aduros** [comment]
After some discussion, I think maybe the best solution for the web runtime is:

1. Use an in-memory storage so that reading back from disk never fails. This brings parity with the native runtime.
2. Show a warning to the player when localStorage fails. We don't have a way to show UIs in the web runtime yet, but this is a good motivation to work on it :smiley: 

This behavior might change in the future, so for now games *should* assume that `diskw` can return 0 if storage isn't supported.
