### ISSUE TITLE
Games update at ~30fps due to Firefox throttling `setTimeout`

### ISSUE THREAD

**Issue by DenialAdams** [aduros/wasm4#492]
https://github.com/aduros/wasm4/blob/c82cfb896fe11db7c2d7626a8275ec2d197a9674/runtimes/web/src/ui/app.ts#L489

See this stackoverflow post from 2019 (which was incorrectly marked as a duplicate):
https://stackoverflow.com/questions/59446882/firefox-is-throttling-setinterval

And a firefox bug that I filed which contains reproduction steps:
https://bugzilla.mozilla.org/show_bug.cgi?id=1783950

---

It seems like updating the game in requestAnimationFrame() might allow us to update at 60fps, but as the stack overflow post points out requestAnimationFrame() is probably capped to the refresh rate of the display, which means on a 30hz panel updating the game would not happen smoothly.

---

One thing that we can do that would probably mitigate this is to call `update` multiple times in one `loop` if we are behind. In terms of frame times this would be janky, but at least the game won't run in slow motion. I can work on an example of this.

**Comment by DenialAdams** [comment]
Another thing to say here is I think that this problem may have surfaced as a result of https://github.com/aduros/wasm4/commit/aa3ad64dfa395ab3d14d341ee350235c7731513b, which rewrote the frame scheduler and introduced the `setTimeout` call. That commit also explicitly mentions that the `requestAnimationFrame` approach is not viable.

**Comment by JerwuQu** [comment]
My guess before looking into it much is that the way `requestAnimationFrame` was used back then wouldn't render things in advance if needed to keep up with the 60hz pace.

Basically, in addition to a `lastFrameMs` you'd have a `frameOffsetMs` that would get added to when a frame lags behind so that the next one gets rendered in advance. This way you should never drop any frames.

I could implement this, try it, and make a PR if I have time now during jam week.

**Comment by aduros** [comment]
Should be fixed on latest hopefully! Please re-open if it's still happening.
