### ISSUE TITLE
Rust: text function and button characters - the trait bound `[u8; 16]: AsRef<str>` is not satisfied

### ISSUE THREAD

**Issue by benc-uk** [aduros/wasm4#590]
Adding the hex codes to show the buttons/arrows results in an error on Rust

```rust
wasm4::text(b"Press \x80 to jump!", 10, 10);
```

Error:
```
error[E0277]: the trait bound `[u8; 16]: AsRef<str>` is not satisfied
   --> src/game.rs:49:25
    |
49  |             wasm4::text(b"Press \x80 to jump!", 10, 10);
    |             ----------- ^^^^^^^^^^^^^^^^^^^^^^ the trait `AsRef<str>` is not implemented for `[u8; 16]`
    |             |
    |             required by a bound introduced by this call
    |
    = help: the following other types implement trait `AsRef<T>`:
              [T; N]
              [T]
    = note: required for `&[u8; 16]` to implement `AsRef<str>`
```

I'm using `rustc 1.65.0 (897e37553 2022-11-02)` on Ubuntu Linux

**Comment by DenialAdams** [comment]
https://doc.rust-lang.org/stable/std/str/fn.from_utf8_unchecked.html

`from_utf8_unchecked` on the byte st will probably work it work, although it is clunky

**Comment by SLiV9** [comment]
Yeah `str::from_utf8_unchecked` is currently the only way to draw the buttons in Rust. Doing so is undefined behavior, but it does seem to work in practice. The underlying issue is that Rust strings have to be valid UTF-8, but WASM-4 expects to be passed strings encoded with ISO-8859-1 (https://github.com/aduros/wasm4/issues/509).

Alternatively you could manually edit `wasm4.rs` by replacing `str` with `[u8]`:
```rust
pub fn text<T: AsRef<[u8]>>(text: T, x: i32, y: i32) {
    let text_ref = text.as_ref();
    unsafe { extern_text(text_ref.as_ptr(), text_ref.len(), x, y) }
}
```
But this would mean that `text("hello", 10, 10)` no longer compiles; you'd need `text(b"hello", 10, 10)`.
