### ISSUE TITLE
Lua cartridge support

### ISSUE THREAD

**Issue by aduros** [aduros/wasm4#97]
Would this be useful for anyone? Lua seems to be the lingua franca of fantasy consoles, so it might help drive adoption?

Implementation-wise it would be a little different since it's interpreted. We could provide a prebuilt cart.wasm written in C containing the Lua runtime. The *.lua files would then be injected into this cart.wasm somehow to produce the final cart.

The nice thing about this approach is that Lua carts would require no compiler toolchain to setup.

**Comment by eXponenta** [comment]
Compile tools will still required, or you will need has CLI 
with wasm recompiler that will replace placeholder for lua source.

You should store LUA source because there are not IO in API.
If  IO will be - this will hacky, because you allow share resources inside/outside cart files.

Anyway you cannot compile Lua onto 64kb :)), because i not seen wasm with luavm less that 200kb

Conclusion:
 LUA is bad idea. It requiring use bigger taht cart runtime that already not allowed or require store LuaRuntime inside player.
Then main idea of wasm4 - cart is single file in binary representation on pure wasm, and use a lua outside itkills the whole point.

**Comment by MaxGraey** [comment]
The main highlight of wasm4 is WebAssembly. Even the name reflects this. If you add Lua, everyone will firmly associate this project with another pico8 clone IMO

**Comment by aduros** [comment]
> Compile tools will still required, or you will need has CLI with wasm recompiler that will replace placeholder for lua source.

That's the idea, to allow injecting Lua source into a prebuilt `lua-cart.wasm` using a `w4` CLI command. It wouldn't involve adding anything Lua-specific to the runtime.

Anyways, this would probably be a pain to implement. I'm not planning on it unless there's enough demand.

**Comment by aduros** [comment]
Supplanted by #204
